### ISSUE TITLE
Input tuple fields of variant data types not supported

### ISSUE THREAD

**Issue by JayatiTiwari** [tomdz/storm-esper#4]
The existing `ofType(Class<?> type)` method supports only a single data type for all the fields in the input tuple.

```
public AliasedInputBuilder ofType(Class<?> type)
{
    for (String fieldName : fieldNames) {
        fieldTypes.put(fieldName, type.getName());
    }
    return new AliasedInputBuilder(bolt, streamId, fieldTypes);
}
```

I have added and tested another method to support different data type for each field in the input tuple.

```
public AliasedInputBuilder ofTypes(Class<?>... types)
{
    if(fieldNames.length == types.length) {
        for(int i = 0; i<fieldNames.length;i++) {
            fieldTypes.put(fieldNames[i], types[i].getName());
            }   
        }
    return new AliasedInputBuilder(bolt, streamId, fieldTypes);
}
```

Sample Usage :

If the input stream is "spout" emitting tuples of the form [inputField1, inputField2], where inputField1 is of the type String and inputField2 is of the type Date, then we'll have the declaration as : 

```
EsperBolt bolt = new EsperBolt.Builder()
                          .inputs().aliasComponent("spout").withFields("inputField1",  inputField2").ofTypes(java.lang.String.class, java.util.Date.class).toEventType("Test")
```

and so on.

**Comment by tomdz** [comment]
This is already supported. The `withFields` method creates a scoped sub-builder just for those fields, for which you then call `ofTypes`. The result of `ofTypes` is an un-scoped builder on which you can call `withFields` again. E.g. your example would look like this:

```
new EsperBolt.Builder()
    .inputs()
        .aliasComponent("spout1")
        .withField("inputField1").ofType(String.class)
        .withField("inputField2").ofType(Date.class)
```
